# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Trinitas' do
    
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Trinitas
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'

  # Swift 3
  pod 'SwiftKeychainWrapper', :git=> 'https://github.com/jrendel/SwiftKeychainWrapper.git', :branch=>'master'

end
